services:
  - type: web
    name: discord-message-monitor
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_DATABASE
        value: false
      - key: DISCORD_TOKEN
        sync: false
